[[biber_bin]]
arch = "x86_64"
git-tree-sha1 = "716fcd1bfe883a5a9c5e05b34a62539b9913b917"
os = "macos"

    [[biber_bin.download]]
    sha256 = "675fb93a2d8cfa52533d4b20423bf18ff1b799693466b91e92e115667bb9297d"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/2.14%2B1/biber-2.14+1-x86_64-apple-darwin14.tar.gz"
[[biber_bin]]
arch = "x86_64"
git-tree-sha1 = "55e62711a9a99b7fdada0d255c157bd10913b7f0"
libc = "glibc"
os = "linux"

    [[biber_bin.download]]
    sha256 = "5acadb273c686d2e10ba8ce3c587891a627bf509da4f576bb1dc29d3592cbc91"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/2.14%2B1/biber-2.14+1-x86_64-linux-gnu.tar.gz"
[[biber_bin]]
arch = "x86_64"
git-tree-sha1 = "d62a5f5a7456fd60110bd1cfc392dc6a264422b6"
os = "windows"

    [[biber_bin.download]]
    sha256 = "831938bacb5c6a3de9894983b996e09450a7dd927afafda149a3204e2bcf39fd"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/2.14%2B1/biber-2.14+1-x86_64-w64-mingw32.tar.gz"

[[tectonic_bin]]
arch = "x86_64"
git-tree-sha1 = "a4ce7276079c3429780a79c694e2e0f008f30c17"
libc = "glibc"
os = "linux"

    [[tectonic_bin.download]]
    sha256 = "4c35a260fa56dc561724736fd0df8b938bbf5da0a29aea56df6eb8e06074244a"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/tectonic-0.5.1%2B1/tectonic-0.5.1+1-x86_64-linux-gnu.tar.gz"
[[tectonic_bin]]
arch = "x86_64"
git-tree-sha1 = "1e7b2fb4271ad40bbd81fe323cc45cadecb98efd"
os = "windows"

    [[tectonic_bin.download]]
    sha256 = "e231ff8d07e8dff492e9e74247d75e443e58c228fa4fcfd906edba448f6608e7"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/tectonic-0.5.1%2B1/tectonic-0.5.1+1-x86_64-w64-mingw32.tar.gz"
[[tectonic_bin]]
arch = "x86_64"
git-tree-sha1 = "a9eb0901d7076f72768d074c848fe5cae945d099"
os = "macos"

    [[tectonic_bin.download]]
    sha256 = "421bdf8edbd0bc914b9cd369cf5774a5e21b3117053c18cf55fe739e1277dd01"
    url = "https://github.com/MichaelHatherly/Tectonic.jl/releases/download/tectonic-0.5.1%2B1/tectonic-0.5.1+1-x86_64-apple-darwin14.tar.gz"
